name: deploy-carrinho

on:
  push:
    branches:
      - main
    paths:
      - 'packages/carrinho/**'

defaults:
  run:
    working-directory: packages/carrinho

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [app, carrinho, produtos]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Build the app
        run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Copy files to  production website with AWS CLI
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/carrinho/latest

      - name: Create invalidation for index.html
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --path "/carrinho/latest/index.html"

 